### ISSUE TITLE
seedsファイルに穴があったので直す

### ISSUE THREAD

**Issue by DaisukeShinoku** [yuki-snow1823/diary#102]
```
rails db:migrate:reset
rails db:seed
```
を繰り返し行った場合に、開発者のuserのauto_incrementの値に関係なく、user_id = 1から順番にjournalを作成しようとするので場合によっては全てのjournalのcreate時に`Validation failed: User must exist`となってjournalが作成されない

**Comment by yuki-snow1823** [comment]
@DaisukeShinoku 
こういうご提案ありがとうございます！！！

**Comment by DaisukeShinoku** [comment]
https://github.com/yuki-snow1823/diary/pull/103
