### ISSUE TITLE
【複数作業あり】Userの一覧ページを作る（詳細ページより軽作業）

### ISSUE THREAD

**Issue by yuki-snow1823** [yuki-snow1823/diary#107]
ユーザーの一覧ページを作りましょう。

## ページに必要な情報
- ユーザーの名前
- ユーザーの詳細ページへのリンク #104 ができるまではハリボテでOK

## マイルストーン
1. ユーザーの一覧取得のGraphQL Queryを作る（#17 の[このファイル](backend/app/graphql/types/query_type.rb) が参考になりそう）
2.  Reactのuserの一覧ページを作る（一旦何も出なくていい）
3.  2のuserの一覧ページから1のQueryを使ってユーザーの情報を表示

PRを小分けして作ってください(__)

**Comment by DaisukeShinoku** [comment]
[バックエンドは実装してみた](https://github.com/yuki-snow1823/diary/pull/115)のですが、
誰かフロントやりたい方いますかあ！

**Comment by DaisukeShinoku** [comment]
フロント、仮実装だけしてる
ここから引き継いでもらってもいいし、新たにブランチ切ってもいいしで、やり方含めてお任せしたいお気持ち

https://github.com/yuki-snow1823/diary/pull/116

**Comment by yuki-snow1823** [comment]
@DaisukeShinoku 
そのまま進めていただいて大丈夫そう（ありがたい）です！
