### ISSUE TITLE
Prettierの設定を見直してカンマがつかないようにしたい

### ISSUE THREAD

**Issue by yuki-snow1823** [yuki-snow1823/diary#14]
そしてフォーマットをかけ直したい

**Comment by mpg-shu-shikata** [comment]
@yuki-snow1823 
> Prettierの設定を見直してカンマがつかないようにしたい

save時、末尾にカンマがつかないようにしたいということでしょうか？👀

**Comment by yuki-snow1823** [comment]
@mpg-shu-shikata 
そうです！自分のローカルの設定なのか、このプロジェクトの設定なのか保存時（ショートカットキーでフォーマットかけたタイミングも）にカンマついているので、なんとかしたいなーと！

**Comment by yuki-snow1823** [comment]
@komaitaira が #47 で対応してくれました。感謝！
