### ISSUE TITLE
全てのオリジンからのリソースアクセス許可を、Reactからのみの許可にする

### ISSUE THREAD

**Issue by yuki-snow1823** [yuki-snow1823/diary#16]
現在、Rails側で全てのオリジンからのリソースアクセス許可を設定してしまっている。

https://github.com/yuki-snow1823/diary/blob/05a63e756b690fd258a106fa67bc25c960463e07/backend/config/initializers/cors.rb#L10

ここを本番環境の場合はVercelのURLに、開発環境の場合はlocalhost:8080に指定するようにして欲しいです。

同一オリジンポリシー - ウェブセキュリティ | MDN 
https://developer.mozilla.org/ja/docs/Web/Security/Same-origin_policy

ここら辺が参考になりそうです。

RailsでAPIにCORSを設定する - Qiita 
https://qiita.com/yumikokh/items/b5fd604e12720027b4d5

**Comment by RouxRhett** [comment]
fix-cors-conf ブランチで作業中
https://github.com/yuki-snow1823/diary/blob/fix-cors-conf/backend/config/initializers/cors.rb

**Comment by yuki-snow1823** [comment]
@RouxRhett 
まだプルリク作っていただいてない中で恐縮ですが、ローカルホストや本番のURLは使い回す気がしたので、diary.ymlみたいな設定ファイルにまとめておいて、そこから呼び出してあげると良さそうだと思いました🙆‍♂️

もしかしたら設定ファイルだけ今日作っちゃうかもですd(￣ ￣)
