### ISSUE TITLE
日本時刻にしてほしい

### ISSUE THREAD

**Issue by yuki-snow1823** [yuki-snow1823/diary#29]
config timezone あたりだったかを直す...

rails タイムゾーンとかを調べていただくと出来るはずです。
tokyoになろう...

**Comment by yuki-snow1823** [comment]
ActiveRecord周りで何か落とし穴があるかも？

**Comment by yuki-snow1823** [comment]
### 確認方法
- graphqlでクリエイトしたデータが正しい時刻になっているか

**Comment by isoiso-isobeage** [comment]
https://github.com/yuki-snow1823/diary/pull/31
