### ISSUE TITLE
開発環境で謎のエラー ActionController::RoutingError (No route matches [GET] "/ws"): が出る

### ISSUE THREAD

**Issue by yuki-snow1823** [yuki-snow1823/diary#30]
未調査
https://teratail.com/questions/283384?link=qa_related_pc

**Comment by DaisukeShinoku** [comment]
@yuki-snow1823 

[creat-react-appのissue](https://github.com/facebook/create-react-app/issues/11779)   にもなっていますが、
サクッと解決するなら下記になるかなと思います。

https://github.com/facebook/create-react-app/issues/11779#issuecomment-998322739
![スクリーンショット 2023-05-07 15 58 40](https://user-images.githubusercontent.com/62245694/236662785-cba0023f-5ae8-46d5-b683-a7a7c1fd8e45.png)

**Comment by yuki-snow1823** [comment]
@DaisukeShinoku ありがとうございます！これやってみてもダメだったんですよね〜（その旨書けば良かった）もう一度やってみます！

**Comment by DaisukeShinoku** [comment]
@yuki-snow1823 
今日（6/17）の午後に同期的にやりませう
