### ISSUE TITLE
seedファイルを作る

### ISSUE THREAD

**Issue by komaitaira** [yuki-snow1823/diary#75]
ログインの確認方法とかで下記をcliで実行しているが、seedで作成されてると楽。その他、ユーザー以外のデータもあれば適宜seedに追加できるとベター
`$ curl -X POST http://localhost:3000/auth -d '[name]=test&[email]=test@example.com&[password]=password&[password_confirmation]=password'`

**Comment by yuki-snow1823** [comment]
これはいいGOOD FIRST ISSUE ちょっと募集してみます

**Comment by yuki-snow1823** [comment]
欲しいもの
・ユーザー
・ジャーナル

そしてこれを初回起動時に実行されるように設定する

**Comment by DaisukeShinoku** [comment]
https://github.com/yuki-snow1823/diary/pull/97
