### ISSUE TITLE
記事の投稿機能を作る

### ISSUE THREAD

**Issue by yuki-snow1823** [yuki-snow1823/diary#8]
- ユーザーごとのページで記事作成ができる
- 作成した記事が表示できる
- 作成はGraphQLのmutationを使用する

**Comment by yuki-snow1823** [comment]
1. journalにユーザーのID持たせる
2. GraphQLでjournalの一覧、ユーザーのjournal1つなどを取れるクエリを生やす

**Comment by yuki-snow1823** [comment]
こちら @besumero628 （奈良さん）に着手いただいてます！

**Comment by besumero628** [comment]
@yuki-snow1823 
こちらGraph QLの実装まででとりあえず良いという認識で相違ありませんか。

下記は完了しました。
- journalにユーザーのID持たせる
- GraphQLでjournalの一覧、ユーザーのjournal1つなどを取れるクエリを生やす
- 作成はGraphQLのmutationを使用する

下記はFront側で適切な呼び方をすれば参照可能になるかと存じます。
- ユーザーごとのページで記事作成ができる
- 作成した記事が表示できる

**Comment by yuki-snow1823** [comment]
@besumero628 
ありがとうございました！あとはAPIとフロントですね！
相談しつつ決めていきましょう！

**Comment by yuki-snow1823** [comment]
#35 がマージされたら、自分の方で投稿機能作ってみます。

**Comment by yuki-snow1823** [comment]
https://github.com/yuki-snow1823/diary/pull/17
